name: Azure Static Web Apps Deploy Only

on:
  push:
    branches:
      - master  # or your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Static Files
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Build Angular App with Production Environment
        run: npm run build -- --configuration=production

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WONDERFUL_WAVE_0DBFEA20F }}
          action: "upload"
          app_location: "/"  # repo root
          output_location: "dist/signal-rapp/browser"  # prebuilt static files
